### ISSUE TITLE
Error: refusing to allow a GitHub App to create or update workflow

### ISSUE THREAD

**Issue by bdougie** [shitiomatic/forkbacon#2]
## What is wrong?
When allowing this Action to push to the default branch of my fork,(by removing the --no-push)  it returns the following error. 

[Link to Error](https://github.com/notBdougie/open-sauced/runs/911778834?check_suite_focus=true#step:4:85):

```sh
To https://github.com/notBdougie/open-sauced
 ! [remote rejected] master -> master (refusing to allow a GitHub App to create or update workflow `.github/workflows/assign-yourself.yml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/notBdougie/open-sauced
```

I am attempting to [highlight this Action in a future video](https://github.com/bdougie/gitActionTraction/issues/8) and wanted to start using it in a real use case, but understand it still a WIP but I am happy to help. 

## More details
For my use case, my repo includes other workflow files which require a PAT. I have included the PAT in my workflow, but I am not seeing the entrypoint.sh using a PAT at all. I would be happy to add it but just wanted to confirm first with this issue that I am not overlooking anything. 

[Link to code](https://github.com/notBdougie/open-sauced/blob/master/.github/workflows/sync.yml#L13
):

```yml
    - uses: shitiomatic/forkbacon@master # Prefer using tagged version
      env:
        GITHUB_TOKEN: ${{ secrets.SYNC_TOKEN }}
      with:
        upstream_url: "https://github.com/open-sauced/open-sauced" # Required! Upstream https clone URL
        upstream_branch: "master"   # Upstream Branch to use
        branch: "master"   # Local Branch
        method: "rebase"   # Method to use. Can be `merge`, `merge-ff-only` or `rebase`.
```

## Solution
Add the ability to use a PAT in the GITHUB_TOKEN env. 

My approach would be using curl instead of the "git"CLI. Similar to [this](https://github.com/open-sauced/open-sauced/blob/master/.github/workflows/assign-yourself.yml#L16).

@shitiomatic, let me know you thoughts on this and if there is something I am not considering.
